### ISSUE TITLE
Fatal error: __autoload() is no longer supported, use spl_autoload_register() instead in /var/www/html/Library/Loader.php on line 11

### ISSUE THREAD

**Issue by alucard001** [hatamiarash7/Memcached-Admin#17]
### Describe the bug

`Fatal error: __autoload() is no longer supported, use spl_autoload_register() instead in /var/www/html/Library/Loader.php on line 11`

![Screenshot 2022-08-31 154244](https://user-images.githubusercontent.com/1968244/187621637-26b77434-74b1-4b7c-bb68-07c9e7c06ac9.png)

### To Reproduce

Simply run this docker command:
`docker run --rm -p 8080:80 -e MEMCACHED_HOST='<my_aws_host>' -e MEMCACHED_PORT='11211' hatamiarash7/memcached-admin:master`

It seems that your PHP version is too old.  Please update your Docker image.

Thank you.

**Comment by hatamiarash7** [comment]
Thanks ... I'll fix this

**Comment by hatamiarash7** [comment]
Done!
