### ISSUE TITLE
Fix or suppress PHP warnings

### ISSUE THREAD

**Issue by asdfklgash** [hatamiarash7/Memcached-Admin#44]
There are many PHP warnings:

```
Warning:  A non-numeric value encountered in /var/www/html/Library/Data/Analysis.php on line 56
```
in `/stats.php`

```
Warning: A non-numeric value encountered in /var/www/html/Library/Data/Analysis.php on line 28
Warning: Undefined array key "mem_requested" in /var/www/html/Library/Data/Analysis.php on line 196`
```
in `index.php`

### Environment

Docker image (hatamiarash7/memcached-admin:master@sha256:91a587ae6b6de18b11eb739a48fc145aff312ad2fdccec838b37d9078fee487d)

**Comment by hatamiarash7** [comment]
Hi @asdfklgash 

I'll check them soon. Also, I will be happy if you check it yourself and register a PR :))

**Comment by sambenskin** [comment]
@hatamiarash7 would it be possible to review and merge this in please? these warnings make it harder to use the UI

**Comment by samb-pilotfinance** [comment]
Thank you!
